# ==============================================================================
# Protocol    : Deep State of Mind (DSOM) For My AI
# Author      : Harisfazillah Jamel (LinuxMalaysia)
# Timestamp   : 2026-08-07
# License     : GNU General Public License v3.0
# Standard    : UK English | DBP-standard Bahasa Melayu Malaysia (Piawai)
# ==============================================================================
all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    env: local
    execution_mode: dev
    pr_id: "0"
    cms_domain: cmsfornerd.local
    podman_cms_user: dsom-admin
    podman_cms_uid: 2001
    podman_cms_group: dsom-admin
    podman_cms_gid: 2001
    project_path: "{{ playbook_dir }}/.."
