<?php

declare(strict_types=1);

namespace CmsForNerd\Tests;

use PHPUnit\Framework\TestCase;

final class GitignorePythonArtifactsTest extends TestCase
{
    private string $gitignorePath;
    private string $content;

    protected function setUp(): void
    {
        $this->gitignorePath = dirname(__DIR__) . '/.gitignore';
        $this->content = (string) file_get_contents($this->gitignorePath);
    }

    public function testGitignoreFileExists(): void
    {
        $this->assertFileExists($this->gitignorePath);
    }

    public function testGitignoreIgnoresPythonBytecodeCacheDirectory(): void
    {
        $this->assertMatchesRegularExpression(
            '/^__pycache__\/$/m',
            $this->content,
            '.gitignore must ignore the __pycache__/ directory generated by Python tooling.'
        );
    }

    public function testGitignoreIgnoresCompiledPythonFiles(): void
    {
        foreach (['*.pyc', '*.pyo', '*.pyd'] as $pattern) {
            $this->assertMatchesRegularExpression(
                '/^' . preg_quote($pattern, '/') . '$/m',
                $this->content,
                ".gitignore must contain the '{$pattern}' pattern to ignore compiled Python artifacts."
            );
        }
    }

    public function testPythonIgnorePatternsAreGroupedImmediatelyAfterTheLaboratoryArtifactsBlock(): void
    {
        $this->assertMatchesRegularExpression(
            '/\*\.old\r?\n__pycache__\/\r?\n\*\.pyc\r?\n\*\.pyo\r?\n\*\.pyd\r?\n/',
            $this->content,
            'The new Python ignore patterns must be grouped together directly beneath the existing *.old entry.'
        );
    }

    public function testGitignoreStillIgnoresPreExistingCoreArtifactsAlongsidePythonAdditions(): void
    {
        foreach (['vendor/', 'composer.lock', '.env', '.DS_Store', 'vault/'] as $preExistingPattern) {
            $this->assertStringContainsString(
                $preExistingPattern,
                $this->content,
                "Adding Python ignore patterns must not remove the pre-existing '{$preExistingPattern}' entry."
            );
        }
    }

    public function testGitignoreDoesNotDuplicateThePythonBytecodePatterns(): void
    {
        foreach (['__pycache__/', '*.pyc', '*.pyo', '*.pyd'] as $pattern) {
            $occurrences = substr_count($this->content, $pattern);
            $this->assertSame(
                1,
                $occurrences,
                "Expected exactly one occurrence of '{$pattern}' in .gitignore, found {$occurrences}."
            );
        }
    }
}