#!/usr/bin/env bash

# ==============================================================================
# Protocol    : Deep State of Mind (DSOM) For My AI
# Author      : Harisfazillah Jamel (LinuxMalaysia)
# Timestamp   : 2026-08-07
# License     : GNU General Public License v3.0
# Standard    : UK English | DBP-standard Bahasa Melayu Malaysia (Piawai)
# ==============================================================================
# ==============================================================================
# Protocol    : Deep State of Mind (DSOM) For My AI
# Author      : Harisfazillah Jamel (LinuxMalaysia)
# Timestamp   : 2026-08-01
# License     : GNU General Public License v3.0
# Standard    : UK English | DBP-standard Bahasa Melayu Malaysia (Piawai)
# ==============================================================================
# Idempotent, robust WSL2 telemetry & feedback bridge to Google Jules and GitHub.
# Safe across environments with multiple fallbacks.

set -euo pipefail

# Set umask strictly to restrict permission on created artifacts
umask 077

# Define Colors for dynamic terminal logging
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0;0m'

log_info() {
    echo -e "${BLUE}[INFO] $(date +'%Y-%m-%d %H:%M:%S') - ${1}${NC}"
}

log_success() {
    echo -e "${GREEN}[SUCCESS] $(date +'%Y-%m-%d %H:%M:%S') - ${1}${NC}"
}

log_warn() {
    echo -e "${YELLOW}[WARN] $(date +'%Y-%m-%d %H:%M:%S') - ${1}${NC}" >&2
}

log_error() {
    echo -e "${RED}[ERROR] $(date +'%Y-%m-%d %H:%M:%S') - ${1}${NC}" >&2
}

# 1. Consume unique local telemetry path from argument, fallback to standard path
TELEMETRY_FILE="${1:-/tmp/jules_telemetry.json}"
FALLBACK_REPORT_DIR="data"
FALLBACK_REPORT_FILE="${FALLBACK_REPORT_DIR}/jules_telemetry_report.md"

# Cleanup function registered on exit trap
cleanup() {
    local exit_code=$?
    if (( exit_code != 0 )); then
        log_error "Script execution terminated abnormally with exit status ${exit_code}."
    fi
}
trap cleanup EXIT

# Check if telemetry file is missing or contains failed results
if [[ ! -f "$TELEMETRY_FILE" ]]; then
    log_warn "Telemetry file ${TELEMETRY_FILE} not found. Synthesising failure fallback..."
    mkdir -p "$(dirname "$TELEMETRY_FILE")"
    cat <<EOF > "$TELEMETRY_FILE"
{
  "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')",
  "execution_mode": "dev",
  "pr_id": "0",
  "matrix_results": [
    {
      "distro": "local-fallback",
      "status": "failed",
      "exit_code": 1,
      "logs": "No external matrix runs were executed.",
      "kernel_info": "$(uname -a)",
      "diff": "Clean workspace."
    }
  ]
}
EOF
fi

log_info "Parsing telemetry from ${TELEMETRY_FILE}..."

# Extract values with jq, or use robust sed/grep fallback if jq is missing
HAS_JQ=$(command -v jq >/dev/null 2>&1 && echo "yes" || echo "no")

get_json_field() {
    local field=$1
    if [[ "$HAS_JQ" == "yes" ]]; then
        jq -r ".${field}" "$TELEMETRY_FILE"
    else
        grep -Po '"'"${field}"'"\s*:\s*"\K[^"]+' "$TELEMETRY_FILE" || echo "unknown"
    fi
}

TIMESTAMP=$(get_json_field "timestamp")
EXEC_MODE=$(get_json_field "execution_mode")
PR_ID=$(get_json_field "pr_id")

log_info "Telemetry details: Timestamp=${TIMESTAMP}, Mode=${EXEC_MODE}, PR_ID=${PR_ID}"

# Reject or bypass external sinks unless EXEC_MODE is dev
if [[ "$EXEC_MODE" != "dev" ]]; then
    log_warn "Execution mode is '${EXEC_MODE}' (not dev). Telemetry report dispatch is skipped."
    exit 0
fi

# Determine if any matrix runs failed
ANY_FAILED="no"

# Compile the Markdown report
MD_REPORT="/tmp/jules_telemetry_markdown.md"
rm -f "$MD_REPORT"

# Use stable matrix comment marker to locate and update the prior comment
COMMENT_MARKER="<!-- JULES_MATRIX_TELEMETRY_MARKER_PR_${PR_ID} -->"

{
    echo "# 📊 Local Test Matrix Telemetry Report"
    echo "${COMMENT_MARKER}"
    echo ""
    echo "This report was dynamically generated by the **WSL2 Podman Multi-OS Feedback Pipeline**."
    echo ""
    echo "| Metric | Value |"
    echo "| :--- | :--- |"
    echo "| **Timestamp** | \`${TIMESTAMP}\` |"
    echo "| **Execution Mode** | \`${EXEC_MODE}\` |"
    echo "| **Target Pull Request** | \`#${PR_ID}\` |"
    echo ""
    echo "## 🖥️ Multi-OS Matrix Test Results"
    echo ""
} >> "$MD_REPORT"

# Extract array items
if [[ "$HAS_JQ" == "yes" ]]; then
    NUM_RESULTS=$(jq '.matrix_results | length' "$TELEMETRY_FILE")
    for ((i=0; i<NUM_RESULTS; i++)); do
        DISTRO=$(jq -r ".matrix_results[$i].distro" "$TELEMETRY_FILE")
        STATUS=$(jq -r ".matrix_results[$i].status" "$TELEMETRY_FILE")
        EXIT_CODE=$(jq -r ".matrix_results[$i].exit_code" "$TELEMETRY_FILE")
        LOGS=$(jq -r ".matrix_results[$i].logs" "$TELEMETRY_FILE")
        KERNEL=$(jq -r ".matrix_results[$i].kernel_info" "$TELEMETRY_FILE")
        DIFF=$(jq -r ".matrix_results[$i].diff" "$TELEMETRY_FILE")

        STATUS_EMOJI="✅ PASSED"
        if [[ "$STATUS" != "passed" || "$EXIT_CODE" != "0" ]]; then
            STATUS_EMOJI="❌ FAILED"
            ANY_FAILED="yes"
        fi

        {
            echo "### 🐧 Distribution: \`${DISTRO}\`"
            echo "* **Overall Status:** ${STATUS_EMOJI}"
            echo "* **Command Exit Code:** \`${EXIT_CODE}\`"
            echo "* **Containerized Kernel Info:** \`${KERNEL}\`"
            echo "* **File System Diff Analysis:**"
            echo "  \`\`\`text"
            echo "  ${DIFF}"
            echo "  \`\`\`"
            echo "* **Execution Stdout/Stderr Output:**"
            echo "  \`\`\`text"
            echo "  ${LOGS}"
            echo "  \`\`\`"
            echo ""
        } >> "$MD_REPORT"
    done
else
    # Non-jq fallback parser path
    ANY_FAILED="yes"
    {
        echo "### 🐧 Distribution: \`wsl-localhost-fallback\`"
        echo "* **Overall Status:** ❌ FAILED (Grep Fallback - Parsing incomplete)"
        echo "* **Command Exit Code:** \`1\`"
        echo "* **Containerized Kernel Info:** \`$(uname -a)\`"
        echo "* **Execution Stdout/Stderr Output:**"
        echo "  \`\`\`text"
        echo "  Parsed without JQ. Result marked failed for safety."
        echo "  \`\`\`"
        echo ""
    } >> "$MD_REPORT"
fi

REPORT_CONTENT=$(cat "$MD_REPORT")

# Dispatch to Google Jules Session CLI
if command -v jules >/dev/null 2>&1; then
    log_info "Jules CLI found. Dispatching telemetry to Google Jules using remote new flow..."
    # Invoke supported 'jules remote new' flow passing the report input
    if jules remote new --repo "CMSForNerd/CmsForNerd" --session "${PR_ID}" --report "$REPORT_CONTENT" >/dev/null 2>&1; then
        log_success "Successfully fed telemetry report to Google Jules."
    # Support backward compatible 'feed' as secondary fallback
    elif jules feed --message "$REPORT_CONTENT" >/dev/null 2>&1; then
        log_success "Successfully fed telemetry using backup feed command."
    else
        log_warn "Google Jules remote new/feed dispatch failed."
    fi
else
    # REST feedback request fallback in curl invocation with connection & total request timeouts
    if [[ -n "${JULES_API_URL:-}" && -n "${JULES_API_TOKEN:-}" ]]; then
        log_info "JULES_API_URL found. Sending REST telemetry report with timeouts..."
        if curl -sS --connect-timeout 5 --max-time 15 -X POST -H "Authorization: Bearer ${JULES_API_TOKEN}" -H "Content-Type: application/json" -d "{\"report\": \"${REPORT_CONTENT}\"}" "${JULES_API_URL}" >/dev/null 2>&1; then
            log_success "Successfully transmitted REST telemetry to Google Jules API."
        else
            log_warn "Failed to transmit REST telemetry payload to Jules API endpoint."
        fi
    else
        log_warn "Google Jules CLI not found and JULES_API_URL not specified. Skipping Jules dispatch."
    fi
fi

# Dispatch to GitHub active Pull Request with idempotency
if command -v gh >/dev/null 2>&1 && [[ "$PR_ID" != "0" && -n "${PR_ID}" ]]; then
    log_info "GitHub CLI found. Checking authentication status..."
    if gh auth status >/dev/null 2>&1; then
        log_info "Searching for existing matrix telemetry comment on PR #${PR_ID}..."
        EXISTING_COMMENT_ID=$(gh pr view "$PR_ID" --json comments -q ".comments[] | select(.body | contains(\"${COMMENT_MARKER}\")) | .id" 2>/dev/null | head -n 1 || echo "")

        if [[ -n "$EXISTING_COMMENT_ID" ]]; then
            log_info "Updating prior comment ID: ${EXISTING_COMMENT_ID}..."
            if gh api -X PATCH "repos/{owner}/{repo}/issues/comments/${EXISTING_COMMENT_ID}" -f body="${REPORT_CONTENT}" >/dev/null 2>&1; then
                log_success "Successfully updated existing GitHub comment."
            else
                log_warn "Failed to update prior comment. Falling back to creating new comment."
                gh pr comment "$PR_ID" --body "$REPORT_CONTENT" >/dev/null && log_success "Created new comment fallback." || log_warn "GitHub commenting failed."
            fi
        else
            log_info "Creating a new telemetry comment..."
            if gh pr comment "$PR_ID" --body "$REPORT_CONTENT" >/dev/null 2>&1; then
                log_success "Successfully commented on GitHub PR #${PR_ID}."
            else
                log_warn "Failed to post new comment on PR #${PR_ID}."
            fi
        fi
    else
        log_warn "GitHub CLI ('gh') is not authenticated. Skipping PR comment update."
    fi
else
    log_warn "GitHub CLI not found, or active PR ID is invalid. Skipping GitHub dispatch."
fi

# Save fallback copy locally for offline human developer audit
mkdir -p "$FALLBACK_REPORT_DIR"
cp "$MD_REPORT" "$FALLBACK_REPORT_FILE"
log_success "Saved structured Markdown report locally to: ${FALLBACK_REPORT_FILE}"

# If any matrix distribution failed or JQ was absent, propagate failure exit status
if [[ "$ANY_FAILED" == "yes" ]]; then
    log_error "Telemetry processing complete with distribution failures detected."
    exit 1
fi

log_success "Bidirectional Telemetry & Feedback pipeline processing complete with all green status."
exit 0
